name: main.py

on:
  schedule:
    # Define a cron para rodar de 1 em 1 hora
    - cron: '0 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run script
      run: |
        for i in {1..3}; do python main.py && break || sleep 60; done
